/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import DB.ConsultasDB;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author salva
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    int x,y;
    public VentanaPrincipal() {
        initComponents();
        ConsultasDB.traerTitulo(listaDeTareasJlist);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agregarTareaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaComentario = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeTareasJlist = new javax.swing.JList<>();
        seleccionTareaLabel = new javax.swing.JLabel();
        botonMostrarTarea = new javax.swing.JButton();
        botonActualizarTarea = new javax.swing.JButton();
        botonEliminarTarea = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cajaMostrarTareas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        botonAgregarTarea = new javax.swing.JButton();
        chekEstadoDeTarea = new javax.swing.JCheckBox();
        cajaTextoActualizar = new javax.swing.JTextField();
        refrescarBoton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        salirBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        agregarTareaLabel.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        agregarTareaLabel.setForeground(new java.awt.Color(255, 255, 255));
        agregarTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarTareaLabel.setText("Agregar Tarea");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Comentario");

        cajaTitulo.setBackground(new java.awt.Color(51, 51, 51));
        cajaTitulo.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        cajaTitulo.setForeground(new java.awt.Color(255, 255, 255));

        cajaComentario.setBackground(new java.awt.Color(51, 51, 51));
        cajaComentario.setColumns(20);
        cajaComentario.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        cajaComentario.setForeground(new java.awt.Color(255, 255, 255));
        cajaComentario.setLineWrap(true);
        cajaComentario.setRows(5);
        jScrollPane1.setViewportView(cajaComentario);

        listaDeTareasJlist.setBackground(new java.awt.Color(51, 51, 51));
        listaDeTareasJlist.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        listaDeTareasJlist.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listaDeTareasJlist);

        seleccionTareaLabel.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        seleccionTareaLabel.setForeground(new java.awt.Color(255, 255, 255));
        seleccionTareaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionTareaLabel.setText("Selecciona una tarea");

        botonMostrarTarea.setBackground(new java.awt.Color(51, 51, 51));
        botonMostrarTarea.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        botonMostrarTarea.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarTarea.setText("Mostar Tarea");
        botonMostrarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTareaActionPerformed(evt);
            }
        });

        botonActualizarTarea.setBackground(new java.awt.Color(51, 51, 51));
        botonActualizarTarea.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        botonActualizarTarea.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarTarea.setText("Actualizar Tarea");
        botonActualizarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarTareaActionPerformed(evt);
            }
        });

        botonEliminarTarea.setBackground(new java.awt.Color(51, 51, 51));
        botonEliminarTarea.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        botonEliminarTarea.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarTarea.setText("Eliminar Tarea");
        botonEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTareaActionPerformed(evt);
            }
        });

        cajaMostrarTareas.setBackground(new java.awt.Color(51, 51, 51));
        cajaMostrarTareas.setColumns(20);
        cajaMostrarTareas.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        cajaMostrarTareas.setForeground(new java.awt.Color(255, 255, 255));
        cajaMostrarTareas.setLineWrap(true);
        cajaMostrarTareas.setRows(5);
        jScrollPane3.setViewportView(cajaMostrarTareas);

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Comentarios de Tareas");

        botonAgregarTarea.setBackground(new java.awt.Color(51, 51, 51));
        botonAgregarTarea.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        botonAgregarTarea.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregarTarea.setText("Agregar Tarea");
        botonAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTareaActionPerformed(evt);
            }
        });

        chekEstadoDeTarea.setBackground(new java.awt.Color(0, 0, 0));
        chekEstadoDeTarea.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        chekEstadoDeTarea.setForeground(new java.awt.Color(255, 255, 255));
        chekEstadoDeTarea.setText("Completado");
        chekEstadoDeTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekEstadoDeTareaActionPerformed(evt);
            }
        });

        cajaTextoActualizar.setBackground(new java.awt.Color(51, 51, 51));
        cajaTextoActualizar.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        cajaTextoActualizar.setForeground(new java.awt.Color(255, 255, 255));

        refrescarBoton.setBackground(new java.awt.Color(51, 51, 51));
        refrescarBoton.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        refrescarBoton.setForeground(new java.awt.Color(255, 255, 255));
        refrescarBoton.setText("Refrescar");
        refrescarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarBotonActionPerformed(evt);
            }
        });

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        salirBoton.setBackground(new java.awt.Color(67, 105, 144));
        salirBoton.setFont(new java.awt.Font("Dubai Medium", 1, 14)); // NOI18N
        salirBoton.setForeground(new java.awt.Color(255, 255, 255));
        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaTitulo))
                            .addComponent(jScrollPane2)
                            .addComponent(seleccionTareaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(chekEstadoDeTarea))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaTextoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(botonEliminarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(botonMostrarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(botonAgregarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(botonActualizarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(agregarTareaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refrescarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarTareaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refrescarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(seleccionTareaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMostrarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonActualizarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaTextoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chekEstadoDeTarea))))
                    .addComponent(jScrollPane3))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTareaActionPerformed
        // TODO add your handling code here:
        String seleccion = listaDeTareasJlist.getSelectedValue();
        ConsultasDB.eliminarTarea(listaDeTareasJlist, seleccion);
        ConsultasDB.traerTitulo(listaDeTareasJlist);
    }//GEN-LAST:event_botonEliminarTareaActionPerformed

    private void botonAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTareaActionPerformed
        // TODO add your handling code here:
        String tituloIngresado = cajaTitulo.getText();
        String comentarioIngresado = cajaComentario.getText();
        Integer estadoTarea = 0;
        
        DefaultListModel modelo = new DefaultListModel();
        listaDeTareasJlist.setModel(modelo);
        
        if(tituloIngresado.length() >= 1 && comentarioIngresado.length() >= 1){
            ConsultasDB.agregarTarea(tituloIngresado, comentarioIngresado, estadoTarea);
            ConsultasDB.traerTitulo(listaDeTareasJlist);
            cajaTitulo.setText("");
            cajaComentario.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Por favor rellene los 2 campos (Titulo y comentario)");
        }
    }//GEN-LAST:event_botonAgregarTareaActionPerformed

    private void botonMostrarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTareaActionPerformed
        // TODO add your handling code here:
        cajaMostrarTareas.setText("");
        String seleccion = listaDeTareasJlist.getSelectedValue();
        String resultado = ConsultasDB.mostrarComentario(seleccion);
        cajaMostrarTareas.append(resultado);
        System.out.println(seleccion);
    }//GEN-LAST:event_botonMostrarTareaActionPerformed

    private void botonActualizarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarTareaActionPerformed
        // TODO add your handling code here:
        String seleccion = listaDeTareasJlist.getSelectedValue();
        String textoNuevo = cajaTextoActualizar.getText();
        Boolean estadoTarea = chekEstadoDeTarea.isSelected();
        Integer estadoPasadoInt = estadoTarea?1:0;

        System.out.println("Estado de la tarea: " + estadoTarea);
        System.out.println("Estado tarea en int: " + estadoPasadoInt);
        if(textoNuevo.length() >= 1){
            ConsultasDB.actualizar(listaDeTareasJlist, seleccion, textoNuevo, estadoPasadoInt);
            cajaTextoActualizar.setText("");
            chekEstadoDeTarea.setSelected(false);
            ConsultasDB.traerTitulo(listaDeTareasJlist);
        }
    }//GEN-LAST:event_botonActualizarTareaActionPerformed

    private void chekEstadoDeTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekEstadoDeTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chekEstadoDeTareaActionPerformed

    private void refrescarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarBotonActionPerformed
        // TODO add your handling code here:
        ConsultasDB.traerTitulo(listaDeTareasJlist);
    }//GEN-LAST:event_refrescarBotonActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_salirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarTareaLabel;
    private javax.swing.JButton botonActualizarTarea;
    private javax.swing.JButton botonAgregarTarea;
    private javax.swing.JButton botonEliminarTarea;
    private javax.swing.JButton botonMostrarTarea;
    private javax.swing.JTextArea cajaComentario;
    private javax.swing.JTextArea cajaMostrarTareas;
    private javax.swing.JTextField cajaTextoActualizar;
    private javax.swing.JTextField cajaTitulo;
    private javax.swing.JCheckBox chekEstadoDeTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaDeTareasJlist;
    private javax.swing.JButton refrescarBoton;
    private javax.swing.JButton salirBoton;
    private javax.swing.JLabel seleccionTareaLabel;
    // End of variables declaration//GEN-END:variables
}
